{% set version = "6.11.2" %}

package:
  name: qt6-gtk-platformtheme
  version: {{ version }}

source:
  # We only need to download the smaller qt-base, not qt-main for this plugin
  url: https://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/qtbase-everywhere-src-{{ version }}.tar.xz
  sha256: 5b2e00eccaf5a4d8c14134ffa0ea8dfd0a35ae1ffc7f8d87fa4305a1ed23cf22


build:
  number: 0
  skip: true  # [not linux]
  # ppc64le not yet built for qt6
  skip: true  # [ppc64le]
  detect_binary_files_with_prefix: true
  run_exports:
    - {{ pin_subpackage('qt6-gtk-platformtheme', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make                               # [unix]
    - jom                                # [win]
    - pkg-config
    - ninja
    - perl
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - qt6-main {{ version }}             # [build_platform != target_platform]
  host:
    - qt6-main {{ version }}
    - glib
    - gtk3
    - pango
    - gdk-pixbuf
  run:
    # We want to be pinned to the exact qt version
    - qt6-main {{ version }}

test:
  commands:
    - test -f "${PREFIX}/lib/qt6/plugins/platformthemes/libqgtk3${SHLIB_EXT}"

about:
  home: http://qt-project.org
  license: LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
  license_file:
    - LICENSES/LGPL-3.0-only.txt
    - LICENSES/GPL-2.0-only.txt
    - LICENSES/GPL-3.0-only.txt
  summary: Qt GTK3 platform theme
  dev_url: https://github.com/qt/qtbase/tree/5.15/src/plugins/platformthemes/gtk3


extra:
  recipe-maintainers:
    - conda-forge/qt-main
  feedstock-name: qt-gtk-platformtheme
